### ISSUE TITLE
Stretching images when using fixed width and height

### ISSUE THREAD

**Issue by simonhamp** [meatpaste/imgsizer#4]
The old imgsizer used to crop images to the desired size _without_ skewing the image to fit the new dimensions.

Can this be re-implemented easily? Perhaps as a parameterised option?

**Comment by meatpaste** [comment]
Thanks for your feedback, I don't use that feature personally but I'll leave this open for the future.

**Comment by stevesweets** [comment]
Yeah, have found myself needing this, but also am struggling to find and old version that did it and didn't crop.   I know i had a bit of code that did it on another script, which i think i called a 'nocrop' option.... will go a-hunting and make this work.

**Comment by abhijeetbhushan** [comment]
Hi There,

I am facing the same issue. Old version was used to crop images but in new version my all images are getting resize and due to this images are stretching on the page. It looks so weird. 

Please let me know if we have any fixes so far. I am upgrading an EE 1.X to 3.X and I needed to move upgraded site to live ASAP. But only due to this problem I am on hold.

Any quick suggestion would be appreciated.

Thanks

**Comment by abhijeetbhushan** [comment]
Well,

I got vendor reply in my email:)

This is really weird and don't expect these kind of support from any addon developer.

The functionality which was working in older version and then after getting upgraded version of the same plugin and not having the old functionality in it. But if anyone is asking that why the old functionality is not working then you are asking for money to get you own old feature working?

Ahh... man, it is your addon and publicly available on devot-ee. No one is asking you to enhance new feature in it. We are asking to provide atleast those feature which was already with that plugin in older version.

I am also a developer and also develop addon, but we don;t ask a single penny if there is any wrong with our new upgrade. If there is any feature in old version then that should caryy in new version because people already used that.

It is amazing to see for earning from somewhere which is not justified.

Thanks a lot, I have worked on many addon and I can fix that one as well. I was only asking that you can mention your error and fix in your next release. And if you are providing that kind of support then please remove the plugin suggestion from devot-ee at least.

Thanks

**Comment by meatpaste** [comment]
I will fix the bug for free when I need to use that feature, if you require the bug to be fixed for a commercial project 'urgently' then I believe it is justified to ask for a contribution as you are basically demanding that someone give up their personal time so that you can generate revenue from free, open source software. 

If you aren't happy with that then I suggest looking at a different plugin.

**Comment by abhijeetbhushan** [comment]
Hi Roger,

Don't worry. I have upgraded the plugin and added all the feature again.
I didn't have any issue to give some effort and fix from myself, however I was suggesting for the other. This post is oending from sep 2016 and still you don't have any fix:) and here you are telling me that you'll fix the bug for free but for any urgent the contribution is justified. Then why you haven;t fixed this issue since SEP 2016. I think it was enough time.

Anyways, I have upgraded and it is working fine for me.

Thanks for your replies.

Thanks

**Comment by meatpaste** [comment]
As I said, when "I" need the feature I will fix it. Perhaps you would like to submit a pull request so that the wider world can benefit from your efforts? 

You should consider the fact that without **free** effort by myself and others this plugin would **not exist at all**, and what I do with my own personal time is **up to me**. Your attitude towards this is a little disturbing to be honest.

**Comment by abhijeetbhushan** [comment]
Hi Roger,

Don't take this other manner. There is nothing behind it. I have only concerned that if any feature is available in older version then that should work with new version as well.

That's it.

And I didn't tell anything about your personal time. I have told only about upgraded plugin which has missing old features with it.

Thanks

**Comment by stevesweets** [comment]
Hi Abhijeet,

Glad to hear that you resolved it, could you let us know how it was resolved, or fork the repo and publish the update so others can use it?

I notice you didn't submit a pull request, and you didn't moan at the original developer for not releasing ee3 version for free yet, either.

S
